### ISSUE TITLE
Infinite Windows Opening With Local Server

### ISSUE THREAD

**Issue by JosMGalJr** [arthuro555/THNK#35]
Attempting to run my project utilizing the new local server adapter causes an infinite amount of game windows to spawn. This occurs with and without the "Trigger Once" condition.

**Comment by arthuro555** [comment]
Oh no! The adapter is supposed to have a failsafe for that, by disabling servers from starting on clients it opened... Could you share:

- Your OS
- A screenshot of the events that you are previewing

? That would help investigate the issue, thanks!

**Comment by JosMGalJr** [comment]
I'm on Windows 10 - I have attached screenshots of both the event sheet and the aftermath.
![Event Sheet](https://user-images.githubusercontent.com/24903112/209896495-d36882f8-ffa1-48dd-91ad-ceebcd2f65fa.png)
![Aftermath](https://user-images.githubusercontent.com/24903112/209896517-86adabd3-4749-47bb-b5f6-4ec6f984d212.png)

**Comment by JosMGalJr** [comment]
Understood, thank you for the answer. I got it figured out :D
