### ISSUE TITLE
Game wont start when p2p adapter is used

### ISSUE THREAD

**Issue by User8426** [arthuro555/THNK#37]
Attempting to load the game while previewing as an application or locally via network preview causes the loading screen to freeze at the start. I believe the onFirstSceneLoaded of P2P adapter is causing this. I have removed just that and it loads showing the issue is isolated there. I had a look at the debugger and I get the following error
`Internal crash: TypeError: Class extends value undefined is not a constructor or null`
Attempting a network preview and using developer tools console shows this and a few more errors
![image](https://user-images.githubusercontent.com/79993483/212493058-7552d4bb-9cf6-4b32-bbb1-d5c96ed5e86e.png)

Example: 
[Bug.zip](https://github.com/arthuro555/THNK/files/10418704/Bug.zip)

**Comment by arthuro555** [comment]
You cannot use the adapter if you are not using THNK.
