### ISSUE TITLE
[Bug] Creating object on UI layer

### ISSUE THREAD

**Issue by VegeTato** [arthuro555/THNK#52]
Hello, as the title says, there is a bug in THNK, when you set the events as:
- on server side
  - Client connected → Create ObjectA in UI layer.

The results are:
- When the host player spawn → ObjectA will spawn on UI layer ✅
- When the client player spawn → ObjectA will spawn on Base Layer ❌

Here is a very simple project I made that shows the bug:
[Test.zip](https://github.com/arthuro555/THNK/files/13440277/Test.zip)

**Comment by arthuro555** [comment]
Should be fixed by #57
