### ISSUE TITLE
Cant leave the server after hosting one

### ISSUE THREAD

**Issue by VegeTato** [arthuro555/THNK#63]
https://github.com/arthuro555/THNK/assets/81715237/1f224a2b-c8a8-4f39-88eb-c925ff8cc8ae

If you Host a scene (THNK-P2P), and then go back to main menu (disconnect from the server), and then join a server as a client not a host, the game still thinks you are the host.
As you can see in the video, the game still thinks I am the host in the right preview, even though I left and disconnect from that server.

Events:
![ss2](https://github.com/arthuro555/THNK/assets/81715237/2cf4e6ed-49a9-475f-9bcd-585f2ff50b97)

**Comment by arthuro555** [comment]
Fixed by 422d2ff005a1e55b6de1d692b73915a4ae92bf98
