### ISSUE TITLE
Linking objects to a player

### ISSUE THREAD

**Issue by arthuro555** [arthuro555/THNK#9]
Linking an object to a player is possible by simply setting an object variable to their player ID, but that is pretty inefficient (picking an object by variable is O(n) where n is the amount of objects) and inconvenient (you have to put the same "Variable ID == THNK::CurrentPlayer()" condition all the time 🙄).

Instead, you could link an object to a player, and when the currently picked player is changed, so would the picked objects list to reflect the player's linked objects. Accessing all objects would still be possible via the pick all objects.

**Comment by MyNameIsRinax** [comment]
🧐
